/* Generated by scripts/recover-functions.py; reviewed boundaries in config/recovered-functions.json. */

#define RECOMP_GENERATED_CODE

#include "../gen/recomp_types.h"

#include <stdio.h>

#include <stdlib.h>

extern void sub_0014A83E(void);
extern void sub_0014A85B(void);
extern void sub_0014B794(void);
extern void sub_0018AFB0(void);
extern void sub_0018B1A0(void);
extern void sub_0018B390(void);
extern void sub_0018B580(void);
extern void sub_0018B770(void);
extern void sub_0018B960(void);
extern void sub_0018BB50(void);
extern void sub_0018BD40(void);
extern void sub_0018C1D0(void);
extern void sub_0018C3C0(void);
extern void sub_0018CB40(void);
extern void sub_0018CEB0(void);
extern void sub_0018CF00(void);
extern void sub_0018CF60(void);
extern void sub_0018D0F0(void);
extern void sub_0018E120(void);
extern void sub_0018E410(void);
extern void sub_0018E500(void);
extern void sub_0018E584(void);
extern void sub_00190240(void);
extern void sub_00190490(void);
extern void sub_00190F90(void);
extern void sub_00190FB0(void);
extern void sub_00191020(void);
extern void sub_001910C0(void);
extern void sub_001910E0(void);
extern void sub_00191150(void);
extern void sub_00191270(void);
extern void sub_001912A0(void);
extern void sub_00191390(void);
extern void sub_00191440(void);
extern void sub_00191530(void);
extern void sub_001916B0(void);
extern void sub_001916C0(void);
extern void sub_00191710(void);
extern void sub_00191730(void);
extern void sub_001917B0(void);
extern void sub_001917F0(void);
extern void sub_001918E0(void);
extern void sub_001919C0(void);
extern void sub_00191BA0(void);
extern void sub_00192090(void);
extern void sub_001928D0(void);
extern void sub_00193580(void);
extern void sub_001935C0(void);
extern void sub_001935DF(void);
extern void sub_00193658(void);
extern void sub_00193830(void);
extern void sub_00193C40(void);
extern void sub_00193D10(void);
extern void sub_00193D90(void);
extern void sub_00193F70(void);
extern void sub_00194210(void);
extern void sub_00194520(void);
extern void sub_00194533(void);
extern void sub_00194573(void);
extern void sub_001945D6(void);
extern void sub_0019460A(void);
extern void sub_00194635(void);
extern void sub_00194676(void);
extern void sub_00194780(void);
extern void sub_001948B9(void);
extern void sub_00194913(void);
extern void sub_001949E2(void);
extern void sub_00194ADD(void);
extern void sub_00196800(void);
extern void sub_00196967(void);
extern void sub_00196A65(void);
extern void sub_00196B34(void);
extern void sub_00196B6A(void);
extern void sub_00196B9A(void);
extern void sub_00196C0B(void);
extern void sub_00196C4A(void);
extern void sub_00196C83(void);
extern void sub_00196E80(void);
extern void sub_00196E92(void);
extern void sub_0019701F(void);
extern void sub_00197058(void);
extern void sub_001970CD(void);
extern void sub_00197AAC(void);
extern void sub_00197BCF(void);
extern void sub_00197C50(void);
extern void sub_001A5299(void);
extern void sub_001A52A4(void);
extern void sub_001BDAA9(void);

extern void xbox_outb(uint16_t port, uint8_t value);

extern void xbox_outw(uint16_t port, uint16_t value);

extern void xbox_outl(uint16_t port, uint32_t value);

extern uint8_t xbox_inb(uint16_t port);

extern uint16_t xbox_inw(uint16_t port);

extern uint32_t xbox_inl(uint16_t port);

/**
 * sub_00191270
 * Original: 0x00191270 - 0x0019129D (45 bytes, 9 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
static void body_00191270(void)
{
    int _flags = 0; /* fallback flag var */
    uint32_t _fa = 0, _fb = 0;
    int32_t _fas = 0, _fbs = 0;
    (void)_fa; (void)_fb; (void)_fas; (void)_fbs;

loc_00191270: ;
    eax = MEM32(0x19DCE0);
    eax = MEM32(eax + 0x2268);
    (void)0; /* sfence: cache/ordering hint, nothing to model */
    ecx = MEM32(eax + 0x100410);
    ecx = ecx | 0x10000;
    MEM32(eax + 0x100410) = ecx;

loc_00191290: ;
    _fa = (uint32_t)(MEM32(eax + 0x100410)) & 0xFFFFFFFFu; _fb = (uint32_t)(0x10000) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* test MEM32(eax + 0x100410), 0x10000 (32-bit) */
    if (TEST_NZ(_fa, _fb)) goto loc_00191290; /* jne: not equal / not zero */

loc_0019129C: ;
    esp += 4; return; /* ret */

}


void sub_00191270(void) {
    uint32_t before_stack=g_esp, before_bx=g_ebx, before_si=g_esi, before_di=g_edi, before_bp=g_ebp;
    static RECOMP_TLS int logged;
    body_00191270();
    if (g_esp!=before_stack+4 || g_ebx!=before_bx || g_esi!=before_si || g_edi!=before_di) {
        fprintf(stderr,"[RECOVERED] ABI FAILURE 0x00191270 esp %08X->%08X expected +4; bx %08X->%08X si %08X->%08X di %08X->%08X bp %08X->%08X\n",before_stack,g_esp,before_bx,g_ebx,before_si,g_esi,before_di,g_edi,before_bp,g_ebp); abort();
    }
    if (!logged++) fprintf(stderr,"[RECOVERED] 0x00191270 returned; ABI verified (ESP/EBX/ESI/EDI)\n");
}

/**
 * sub_00191530
 * Original: 0x00191530 - 0x001916A3 (371 bytes, 128 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
static void body_00191530(void)
{
    uint32_t ebp;
    ebp = g_ebp;  /* frameless: caller's frame */
    int _flags = 0; /* fallback flag var */
    uint32_t _fa = 0, _fb = 0;
    int32_t _fas = 0, _fbs = 0;
    (void)_fa; (void)_fb; (void)_fas; (void)_fbs;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_00191530: ;
    esp = esp - 8;
    PUSH32(esp, esi);
    esi = MEM32(0x19DCE0);
    _fa = (uint32_t)(MEM8(esi + 8)) & 0xFFu; _fb = (uint32_t)(4) & 0xFFu;
    _fas = (int32_t)(int8_t)(_fa); _fbs = (int32_t)(int8_t)(_fb); /* test MEM8(esi + 8), 4 (8-bit) */
    ecx = MEM32(esi);
    PUSH32(esp, edi);
    if (TEST_Z(_fa, _fb)) goto loc_00191569; /* je: equal / zero */

loc_00191543: ;
    eax = MEM32(esi + 0x350);
    edi = MEM32(eax + 4);
    edx = MEM32(esi + 0x354);
    ecx = ecx - edi;
    edx = edx + ecx;
    MEM32(esi + 0x354) = edx;
    eax = MEM32(eax + 4);
    POP32(esp, edi);
    MEM32(esi) = eax;
    POP32(esp, esi);
    esp = esp + 8;
    esp += 12; return; /* ret 8 */

loc_00191569: ;
    edx = MEM32(esp + 0x18);
    eax = MEM32(esi + 0x34);
    PUSH32(esp, ebx);
    ebx = ecx + edx;
    edx = MEM32(eax);
    eax = MEM32(esi + 0x2264);
    eax = MEM32(eax + 0x44);
    MEM32(esp + 0x10) = edx;
    edx = MEM32(esi + 0x24);
    eax = eax | 0x80000000u;
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(edx) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, edx (32-bit) */
    MEM32(esp + 0xC) = ebx;
    if (CMP_B(_fa, _fb)) goto loc_00191598; /* jb: below (unsigned <) */

loc_00191593: ;
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(esi + 0x28)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(esi + 0x28) (32-bit) */
    if (CMP_B(_fa, _fb)) goto loc_001915AC; /* jb: below (unsigned <) */

loc_00191598: ;
    eax = MEM32(esi + 0x438);
    eax = MEM32(eax + 0x324C);
    eax = eax & 0xFFFFFFFEu;
    eax = eax | 0x80000000u;

loc_001915AC: ;
    edi = MEM32(esi + 0x28);
    ebx = ebx + 0x4000;
    _fa = (uint32_t)(ebx) & 0xFFFFFFFFu; _fb = (uint32_t)(edi) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp ebx, edi (32-bit) */
    if (CMP_B(_fa, _fb)) goto loc_001915F9; /* jb: below (unsigned <) */

loc_001915B9: ;
    ebx = MEM32(esp + 0x18);
    ebx = ebx + ecx;
    _fa = (uint32_t)(ebx) & 0xFFFFFFFFu; _fb = (uint32_t)(edi) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp ebx, edi (32-bit) */
    if (CMP_A(_fa, _fb)) goto loc_001915C9; /* ja: above (unsigned >) */

loc_001915C3: ;
    MEM32(esp + 0xC) = edi;
    goto loc_001915F9;

loc_001915C9: ;
    ecx = ecx - edx;
    MEM32(esi + 0x44) = ecx;
    ecx = MEM32(esi);
    edx = edx & 0xFFFFFFF;
    edx++;
    MEM32(ecx) = edx;
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(esi)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(esi) (32-bit) */
    if (CMP_BE(_fa, _fb)) goto loc_001915E3; /* jbe: below or equal (unsigned <=) */

loc_001915DD: ;
    eax = MEM32(esi + 0x24);
    eax = eax + 4;

loc_001915E3: ;
    ecx = MEM32(esi + 0x24);
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(ecx) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, ecx (32-bit) */
    if (CMP_NE(_fa, _fb)) goto loc_001915ED; /* jne: not equal / not zero */

loc_001915EA: ;
    eax = ecx + 4;

loc_001915ED: ;
    edx = MEM32(esp + 0x1C);
    edx = edx + ecx;
    MEM32(esp + 0xC) = edx;
    MEM32(esi) = ecx;

loc_001915F9: ;
    _fa = (uint32_t)(ecx) & 0xFFFFFFFFu; _fb = (uint32_t)(eax) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp ecx, eax (32-bit) */
    if (CMP_AE(_fa, _fb)) goto loc_0019165C; /* jae: above or equal (unsigned >=) */

loc_001915FD: ;
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(esp + 0xC)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(esp + 0xC) (32-bit) */
    if (CMP_A(_fa, _fb)) goto loc_0019165C; /* ja: above (unsigned >) */

loc_00191603: ;
    ebx = MEM32(0x19E32C);
    eax = MEM32(esi + 0x38);
    PUSH32(esp, ebp);
    ebp = MEM32(esi + 0x4C);
    ebx = ebx >> 1;
    edx = eax + eax * 2;
    ebx = ebx + ecx;
    edx = ebp + edx * 4;
    goto loc_00191620;

    /* nop */

loc_00191620: ;
    edx = MEM32(edx);
    MEM32(esp + 0x20) = edx;
    edx = MEM32(esi + 0x3C);
    eax--;
    eax = eax & edx;
    edx = eax + eax * 2;
    edi = MEM32(ebp + edx * 4 + 4);
    _fa = (uint32_t)(edi) & 0xFFFFFFFFu; _fb = (uint32_t)(ecx) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp edi, ecx (32-bit) */
    edx = ebp + edx * 4;
    if (CMP_AE(_fa, _fb)) goto loc_0019163E; /* jae: above or equal (unsigned >=) */

loc_0019163B: ;
    edi = edi + MEM32(esi + 0x44);

loc_0019163E: ;
    _fa = (uint32_t)(edi) & 0xFFFFFFFFu; _fb = (uint32_t)(ebx) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp edi, ebx (32-bit) */
    if (CMP_BE(_fa, _fb)) goto loc_0019164F; /* jbe: below or equal (unsigned <=) */

loc_00191642: ;
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(esi + 0x38)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(esi + 0x38) (32-bit) */
    if (CMP_EQ(_fa, _fb)) goto loc_0019164F; /* je: equal / zero */

loc_00191647: ;
    edi = MEM32(esp + 0x14);
    _fa = (uint32_t)(MEM32(edx)) & 0xFFFFFFFFu; _fb = (uint32_t)(edi) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp MEM32(edx), edi (32-bit) */
    if (CMP_A(_fa, _fb)) goto loc_00191620; /* ja: above (unsigned >) */

loc_0019164F: ;
    eax = MEM32(esp + 0x20);
    PUSH32(esp, 1);
    PUSH32(esp, eax);
    PUSH32(esp, 0x0019165Bu); RECOMP_ABI_CALL(0x00191440u, sub_00191440); /* call 0x00191440 */

loc_0019165B: ;
    POP32(esp, ebp);

loc_0019165C: ;
    ecx = MEM32(esp + 0xC);
    eax = MEM32(esi + 8);
    ecx = ecx + 0xFFFFFDFCu;
    _fa = (uint32_t)(HI8(eax)) & 0xFFu; _fb = (uint32_t)(8) & 0xFFu;
    _fas = (int32_t)(int8_t)(_fa); _fbs = (int32_t)(int8_t)(_fb); /* test HI8(eax), 8 (8-bit) */
    MEM32(esi + 4) = ecx;
    POP32(esp, ebx);
    if (TEST_Z(_fa, _fb)) goto loc_0019168B; /* je: equal / zero */

loc_00191672: ;
    eax = eax | 0x1000;
    ecx = esi;
    MEM32(esi + 8) = eax;
    PUSH32(esp, 0x00191681u); RECOMP_ABI_CALL(0x001912A0u, sub_001912A0); /* call 0x001912A0 */

loc_00191681: ;
    eax = MEM32(esi);
    POP32(esp, edi);
    POP32(esp, esi);
    esp = esp + 8;
    esp += 12; return; /* ret 8 */

loc_0019168B: ;
    PUSH32(esp, 1);
    PUSH32(esp, 0x00191692u); RECOMP_ABI_CALL(0x00191390u, sub_00191390); /* call 0x00191390 */

loc_00191692: ;
    ecx = esi;
    PUSH32(esp, 0x00191699u); RECOMP_ABI_CALL(0x001912A0u, sub_001912A0); /* call 0x001912A0 */

loc_00191699: ;
    eax = MEM32(esi);
    POP32(esp, edi);
    POP32(esp, esi);
    esp = esp + 8;
    esp += 12; return; /* ret 8 */

}


void sub_00191530(void) {
    uint32_t before_stack=g_esp, before_bx=g_ebx, before_si=g_esi, before_di=g_edi, before_bp=g_ebp;
    static RECOMP_TLS int logged;
    body_00191530();
    if (g_esp!=before_stack+12 || g_ebx!=before_bx || g_esi!=before_si || g_edi!=before_di) {
        fprintf(stderr,"[RECOVERED] ABI FAILURE 0x00191530 esp %08X->%08X expected +12; bx %08X->%08X si %08X->%08X di %08X->%08X bp %08X->%08X\n",before_stack,g_esp,before_bx,g_ebx,before_si,g_esi,before_di,g_edi,before_bp,g_ebp); abort();
    }
    if (!logged++) fprintf(stderr,"[RECOVERED] 0x00191530 returned; ABI verified (ESP/EBX/ESI/EDI)\n");
}

/**
 * sub_001917F0
 * Original: 0x001917F0 - 0x001918D3 (227 bytes, 53 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
static void body_001917F0(void)
{
    int _flags = 0; /* fallback flag var */
    uint32_t _fa = 0, _fb = 0;
    int32_t _fas = 0, _fbs = 0;
    (void)_fa; (void)_fb; (void)_fas; (void)_fbs;

loc_001917F0: ;
    PUSH32(esp, esi);
    esi = MEM32(0x19DCE0);
    eax = MEM32(esi);
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(esi + 4)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(esi + 4) (32-bit) */
    PUSH32(esp, edi);
    if (CMP_B(_fa, _fb)) goto loc_00191804; /* jb: below (unsigned <) */

loc_001917FF: ;
    PUSH32(esp, 0x00191804u); RECOMP_ABI_CALL(0x001916B0u, sub_001916B0); /* call 0x001916B0 */

loc_00191804: ;
    MEM32(eax) = 0xC0180;
    MEM32(eax + 4) = 2;
    ecx = 3;
    MEM32(eax + 8) = ecx;
    MEM32(eax + 0xC) = ecx;
    MEM32(eax + 0x10) = 0x180190;
    MEM32(eax + 0x14) = 4;
    MEM32(eax + 0x18) = 9;
    MEM32(eax + 0x1C) = 0xA;
    MEM32(eax + 0x20) = ecx;
    MEM32(eax + 0x24) = ecx;
    MEM32(eax + 0x28) = 8;
    MEM32(eax + 0x2C) = 0x401A8;
    MEM32(eax + 0x30) = 0xC;
    MEM32(eax + 0x34) = 0x41D6C;
    edi = 0; /* xor self */
    MEM32(eax + 0x38) = edi;
    ecx = MEM32(esi + 4);
    eax = eax + 0x3C;
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(ecx) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, ecx (32-bit) */
    MEM32(esi) = eax;
    if (CMP_B(_fa, _fb)) goto loc_00191870; /* jb: below (unsigned <) */

loc_0019186B: ;
    PUSH32(esp, 0x00191870u); RECOMP_ABI_CALL(0x001916B0u, sub_001916B0); /* call 0x001916B0 */

loc_00191870: ;
    MEM32(eax) = 0x409FC;
    ecx = 1;
    MEM32(eax + 4) = ecx;
    MEM32(eax + 8) = 0x100A50;
    MEM32(eax + 0xC) = edi;
    MEM32(eax + 0x10) = edi;
    MEM32(eax + 0x14) = edi;
    MEM32(eax + 0x18) = 0x3F800000;
    MEM32(eax + 0x1C) = 0x416BC;
    MEM32(eax + 0x20) = ecx;
    MEM32(eax + 0x24) = 0x41E78;
    MEM32(eax + 0x28) = 0x210000;
    MEM32(eax + 0x2C) = 0x41D80;
    MEM32(eax + 0x30) = ecx;
    MEM32(eax + 0x34) = 0x41E68;
    MEM32(eax + 0x38) = 0x7F800000;
    eax = eax + 0x3C;
    PUSH32(esp, edi);
    MEM32(esi) = eax;
    PUSH32(esp, 0x001918D0u); RECOMP_ABI_CALL(0x00190240u, sub_00190240); /* call 0x00190240 */

loc_001918D0: ;
    POP32(esp, edi);
    POP32(esp, esi);
    esp += 4; return; /* ret */

}


void sub_001917F0(void) {
    uint32_t before_stack=g_esp, before_bx=g_ebx, before_si=g_esi, before_di=g_edi, before_bp=g_ebp;
    static RECOMP_TLS int logged;
    body_001917F0();
    if (g_esp!=before_stack+4 || g_ebx!=before_bx || g_esi!=before_si || g_edi!=before_di) {
        fprintf(stderr,"[RECOVERED] ABI FAILURE 0x001917F0 esp %08X->%08X expected +4; bx %08X->%08X si %08X->%08X di %08X->%08X bp %08X->%08X\n",before_stack,g_esp,before_bx,g_ebx,before_si,g_esi,before_di,g_edi,before_bp,g_ebp); abort();
    }
    if (!logged++) fprintf(stderr,"[RECOVERED] 0x001917F0 returned; ABI verified (ESP/EBX/ESI/EDI)\n");
}

/**
 * sub_001918E0
 * Original: 0x001918E0 - 0x001919BE (222 bytes, 50 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
static void body_001918E0(void)
{
    uint32_t ebp;
    ebp = g_ebp;  /* frameless: caller's frame */
    int _flags = 0; /* fallback flag var */
    uint32_t _fa = 0, _fb = 0;
    int32_t _fas = 0, _fbs = 0;
    (void)_fa; (void)_fb; (void)_fas; (void)_fbs;
    ebp = g_seh_ebp; /* fpo_leaf: inherit caller's frame */

loc_001918E0: ;
    PUSH32(esp, ebx);
    PUSH32(esp, esi);
    esi = MEM32(0x19DCE0);
    eax = MEM32(esi);
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(esi + 4)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(esi + 4) (32-bit) */
    PUSH32(esp, edi);
    if (CMP_B(_fa, _fb)) goto loc_001918F5; /* jb: below (unsigned <) */

loc_001918F0: ;
    PUSH32(esp, 0x001918F5u); RECOMP_ABI_CALL(0x001916B0u, sub_001916B0); /* call 0x001916B0 */

loc_001918F5: ;
    MEM32(eax) = 0x42000;
    MEM32(eax + 4) = 0xE;
    MEM32(eax + 8) = 0x44000;
    MEM32(eax + 0xC) = 0x10;
    MEM32(eax + 0x10) = 0x46000;
    MEM32(eax + 0x14) = 0x11;
    MEM32(eax + 0x18) = 0x40000;
    MEM32(eax + 0x1C) = 0xD;
    MEM32(eax + 0x20) = 0x42180;
    MEM32(eax + 0x24) = 7;
    MEM32(eax + 0x28) = 0x442FC;
    MEM32(eax + 0x2C) = 3;
    edx = eax + 0x20;
    eax = 0; /* xor self */
    ebx = esi + 0x201C;
    edi = esi + 0x203C;
    ecx = 8;
    { uint32_t _i; int32_t _st = RECOMP_DF_STEP(4); for (_i = 0; _i < ecx; _i++) MEM32(edi + _i*_st) = eax; edi += ecx * _st; }
    ecx = 0; /* rep stosd */
    edi = ebx;
    edx = edx + 0x1C;
    ecx = 8;
    { uint32_t _i; int32_t _st = RECOMP_DF_STEP(4); for (_i = 0; _i < ecx; _i++) MEM32(edi + _i*_st) = eax; edi += ecx * _st; }
    ecx = 0; /* rep stosd */
    MEM32(ebx) = eax;
    MEM32(esi + 0x2020) = 3;
    MEM32(edx + -12) = 0x86184;
    MEM32(edx + -8) = 3;
    MEM32(edx + -4) = 0xB;
    eax = 0x19;
    MEM32(edx) = 0x1C4184;
    MEM32(edx + 4) = eax;
    MEM32(edx + 8) = eax;
    MEM32(edx + 0xC) = eax;
    MEM32(edx + 0x10) = eax;
    MEM32(edx + 0x14) = eax;
    MEM32(edx + 0x18) = eax;
    MEM32(edx + 0x1C) = 0x11;
    edx = edx + 0x20;
    POP32(esp, edi);
    MEM32(esi) = edx;
    POP32(esp, esi);
    POP32(esp, ebx);
    g_seh_ebp = ebp; sub_001917F0(); return; /* tail jmp 0x001917F0 */

}


void sub_001918E0(void) {
    uint32_t before_stack=g_esp, before_bx=g_ebx, before_si=g_esi, before_di=g_edi, before_bp=g_ebp;
    static RECOMP_TLS int logged;
    body_001918E0();
    if (g_esp!=before_stack+4 || g_ebx!=before_bx || g_esi!=before_si || g_edi!=before_di) {
        fprintf(stderr,"[RECOVERED] ABI FAILURE 0x001918E0 esp %08X->%08X expected +4; bx %08X->%08X si %08X->%08X di %08X->%08X bp %08X->%08X\n",before_stack,g_esp,before_bx,g_ebx,before_si,g_esi,before_di,g_edi,before_bp,g_ebp); abort();
    }
    if (!logged++) fprintf(stderr,"[RECOVERED] 0x001918E0 returned; ABI verified (ESP/EBX/ESI/EDI)\n");
}

/**
 * sub_00190240
 * Original: 0x00190240 - 0x00190335 (245 bytes, 59 insns)
 * CC: cdecl, 0 params, returns int_or_void
 * Frame: fpo_leaf
 */
static void body_00190240(void)
{
    int _flags = 0; /* fallback flag var */
    uint32_t _fa = 0, _fb = 0;
    int32_t _fas = 0, _fbs = 0;
    (void)_fa; (void)_fb; (void)_fas; (void)_fbs;

loc_00190240: ;
    eax = MEM32(esp + 4);
    _fa = (uint32_t)(LO8(eax)) & 0xFFu; _fb = (uint32_t)(0x10) & 0xFFu;
    _fas = (int32_t)(int8_t)(_fa); _fbs = (int32_t)(int8_t)(_fb); /* test LO8(eax), 0x10 (8-bit) */
    PUSH32(esp, ebx);
    ebx = MEM32(0x19DCE0);
    ecx = MEM32(ebx + 8);
    if (TEST_Z(_fa, _fb)) goto loc_0019025A; /* je: equal / zero */

loc_00190252: ;
    ecx = ecx | 0x200;
    goto loc_00190260;

loc_0019025A: ;
    ecx = ecx & 0xFFFFFDFFu;

loc_00190260: ;
    eax = eax & 0xFFFFFFEFu;
    MEM32(ebx + 8) = ecx;
    MEM32(ebx + 0x2018) = eax;
    if ((eax != 0)) goto loc_00190331; /* jne: not equal / not zero */

loc_00190272: ;
    MEM32(0x19DED8) = MEM32(0x19DED8) | 0x1600;
    eax = MEM32(ebx);
    _fa = (uint32_t)(eax) & 0xFFFFFFFFu; _fb = (uint32_t)(MEM32(ebx + 4)) & 0xFFFFFFFFu;
    _fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* cmp eax, MEM32(ebx + 4) (32-bit) */
    if (CMP_B(_fa, _fb)) goto loc_00190288; /* jb: below (unsigned <) */

loc_00190283: ;
    PUSH32(esp, 0x00190288u); RECOMP_ABI_CALL(0x001916B0u, sub_001916B0); /* call 0x001916B0 */

loc_00190288: ;
    PUSH32(esp, esi);
    PUSH32(esp, edi);
    MEM32(eax) = 0x41EA4;
    MEM32(eax + 4) = 0x3C;
    MEM32(eax + 8) = 0x300B80;
    edi = eax + 0xC;
    PUSH32(esp, 0x19A170);
    ecx = 0xC;
    esi = 0x19A228;
    if (!g_df) { uint8_t *_d = (uint8_t*)XBOX_PTR(edi), *_s = (uint8_t*)XBOX_PTR(esi); uint32_t _n = ecx * 4;
      if (_d + _n <= _s || _s + _n <= _d) memcpy(_d, _s, _n);
      else { uint32_t _i; for (_i = 0; _i < ecx; _i++) MEM32(edi + _i*4) = MEM32(esi + _i*4); }
      esi += ecx * 4; edi += ecx * 4; }
    else { uint32_t _i; for (_i = 0; _i < ecx; _i++) MEM32(edi - _i*4) = MEM32(esi - _i*4); esi -= ecx * 4; edi -= ecx * 4; }
    ecx = 0; /* rep movsd */
    esi = eax + 0x3C;
    PUSH32(esp, 0x400840);
    PUSH32(esp, esi);
    PUSH32(esp, 0x001902C0u); RECOMP_ABI_CALL(0x00190FB0u, sub_00190FB0); /* call 0x00190FB0 */

loc_001902C0: ;
    PUSH32(esp, 0x19A170);
    PUSH32(esp, 0x400880);
    eax = esi + 0x44;
    PUSH32(esp, eax);
    PUSH32(esp, 0x001902D3u); RECOMP_ABI_CALL(0x00190FB0u, sub_00190FB0); /* call 0x00190FB0 */

loc_001902D3: ;
    PUSH32(esp, 0x19A170);
    PUSH32(esp, 0x4008C0);
    ecx = esi + 0x88;
    PUSH32(esp, ecx);
    PUSH32(esp, 0x001902E9u); RECOMP_ABI_CALL(0x00190FB0u, sub_00190FB0); /* call 0x00190FB0 */

loc_001902E9: ;
    PUSH32(esp, 0x19A170);
    PUSH32(esp, 0x400900);
    edx = esi + 0xCC;
    PUSH32(esp, edx);
    PUSH32(esp, 0x001902FFu); RECOMP_ABI_CALL(0x00190FB0u, sub_00190FB0); /* call 0x00190FB0 */

loc_001902FF: ;
    eax = 0; /* xor self */
    MEM32(esi + 0x110) = 0x1009D0;
    MEM32(esi + 0x114) = eax;
    MEM32(esi + 0x118) = eax;
    MEM32(esi + 0x11C) = 0x3F800000;
    MEM32(esi + 0x120) = eax;
    esi = esi + 0x124;
    POP32(esp, edi);
    MEM32(ebx) = esi;
    POP32(esp, esi);

loc_00190331: ;
    POP32(esp, ebx);
    esp += 8; return; /* ret 4 */

}


void sub_00190240(void) {
    uint32_t before_stack=g_esp, before_bx=g_ebx, before_si=g_esi, before_di=g_edi, before_bp=g_ebp;
    static RECOMP_TLS int logged;
    body_00190240();
    if (g_esp!=before_stack+8 || g_ebx!=before_bx || g_esi!=before_si || g_edi!=before_di) {
        fprintf(stderr,"[RECOVERED] ABI FAILURE 0x00190240 esp %08X->%08X expected +8; bx %08X->%08X si %08X->%08X di %08X->%08X bp %08X->%08X\n",before_stack,g_esp,before_bx,g_ebx,before_si,g_esi,before_di,g_edi,before_bp,g_ebp); abort();
    }
    if (!logged++) fprintf(stderr,"[RECOVERED] 0x00190240 returned; ABI verified (ESP/EBX/ESI/EDI)\n");
}
