/*
 * TTD dx query: every write to a guest VA, across all 29 aliases.
 *
 * Run inside a TTD trace by `tools/ttd/ttd-query.py`, which loads this file with
 * `.scriptload` and calls the exported functions through `dx`.  The debugger's
 * JavaScript engine is the only place the TTD objects exist, so this file is the
 * part that has to live there; everything else (argument parsing, alias
 * arithmetic, reporting) stays in Python where it can be tested without a trace.
 *
 * The engine is old and strict about syntax: `var` only (no `let`/`const`), no
 * `for...of` (use an index loop over a snapshot), no template literals, no arrow
 * functions, and no trailing commas.  A syntax error here is reported as
 * "Unable to bind name" on every later call, which reads like a missing function
 * rather than a parse failure -- so the file is kept to that subset deliberately.
 *
 * Design notes that are load-bearing:
 *
 *   - The alias set is passed in, not computed here.  Python owns
 *     `tools/ttd/aliases.py` and its tests; a second implementation of the mirror
 *     arithmetic inside JavaScript would be a second thing to get wrong, and the
 *     one that runs is the one nobody can unit-test.
 *
 *   - One query per alias, not one query over a span.  `TTD.Memory(lo, hi, "w")`
 *     over the whole span from the first alias to the last would return every
 *     write in between -- hundreds of MB of unrelated memory -- and the report
 *     would be dominated by noise while the per-alias attribution, which is the
 *     entire point, would be lost.
 *
 *   - Counts are reported, not truncated silently.  A caller must be able to tell
 *     "zero writes" from "stopped after N".  `maxHits` bounds the work and the
 *     record says when the bound was reached.
 */

// Emitted records are pipe-delimited and prefixed, so the Python side parses a
// stream that also carries the debugger's own chatter without depending on it.
var PREFIX_EVENT = 'TTDWRITE';
var PREFIX_SUMMARY = 'TTDALIAS';
var PREFIX_CONTROL = 'TTDCONTROL';


function _hex(value, width) {
    var s = value.toString(16);
    while (s.length < width) { s = '0' + s; }
    return s;
}

function _addr64(value) { return '0x' + _hex(value, 16); }

function _log(line) { host.diagnostics.debugLog(line + '\n'); }

/*
 * Writes observed in [lo, hi) with the given access type.
 *
 * `access` is the debugger's own filter string: "w" write, "r" read, "rw" both,
 * "e" execute.  The caller decides; this function does not reinterpret it.
 */
function _enumerate(lo, hi, access, maxHits) {
    var query = host.currentSession.TTD.Memory(lo, hi, access);
    var hits = [];
    var truncated = false;
    for (var event of query) {
        if (hits.length >= maxHits) { truncated = true; break; }
        hits.push(event);
    }
    return { hits: hits, truncated: truncated };
}
/*
 * One alias: emit every write, then a summary line naming the alias and its count.
 *
 * The summary is emitted even when the count is zero, because "this alias was
 * asked and had no writes" is the observation the absence claim rests on.  A
 * caller that only saw event lines could not distinguish an alias with no writes
 * from an alias that was never queried.
 */
function queryAlias(index, lo, hi, maxHits) {
    var result = _enumerate(lo, hi, 'w', maxHits);
    for (var i = 0; i < result.hits.length; i++) {
        var e = result.hits[i];
        _log(PREFIX_EVENT + '|' + index + '|' + _addr64(e.Address) + '|'
             + _addr64(e.IP) + '|' + e.Size + '|' + e.ThreadId + '|'
             + e.TimeStart.Sequence + '|' + e.TimeStart.Steps + '|'
             + _hex(e.Value >>> 0, 8));
    }
    _log(PREFIX_SUMMARY + '|' + index + '|' + _addr64(lo) + '|' + _addr64(hi)
         + '|' + result.hits.length + '|' + (result.truncated ? 1 : 0));
    return result.hits.length;
}

/*
 * The whole query: one alias at a time, in the order the caller supplied.
 *
 * `aliasList` is a comma-separated list of 64-bit hex addresses, generated by
 * tools/ttd/aliases.py.  `maxHitsPerAlias` bounds each alias independently, so a
 * pathological alias cannot consume the budget of the others.
 */
function queryAliases(aliasList, maxHitsPerAlias) {
    var text = '' + aliasList;
    var parts = text.split(',');
    var total = 0;
    var asked = 0;
    for (var i = 0; i < parts.length; i++) {
        var token = parts[i].replace(/^\s+|\s+$/g, '');
        if (token.length === 0) { continue; }
        var lo = _parseAddress(token);
        total += queryAlias(i, lo, lo + 4, maxHitsPerAlias);
        asked = asked + 1;
    }
    _log(PREFIX_CONTROL + '|aliases_queried|' + asked);
    _log(PREFIX_CONTROL + '|writes_total|' + total);
    return total;
}

/*
 * Parse an address that may arrive as a number (from a `dx` literal) or as a hex
 * string (from the generated alias list).
 *
 * The numeric case matters: `dx @$scriptContents.f(0x1D3F00)` passes a NUMBER, and
 * stringifying it yields DECIMAL -- so a hex-only parser reads 0x1D3F00 as
 * 1916672 decimal and queries the wrong address.  That is not hypothetical; it is
 * how the negative control first failed, reporting an exception instead of a zero.
 */
function _parseAddress(token) {
    if (typeof token === 'number') { return token; }
    var t = ('' + token).replace(/^\s+|\s+$/g, '').toLowerCase();
    if (t.indexOf('0x') === 0) { t = t.substring(2); }
    if (t.length === 0) { return 0; }
    // Split the 64-bit hex string in halves: JavaScript numbers lose precision
    // above 2^53, and the mirror addresses are far above it.
    var hi = 0;
    var lo = 0;
    if (t.length > 8) {
        hi = parseInt(t.substring(0, t.length - 8), 16);
        lo = parseInt(t.substring(t.length - 8), 16);
    } else {
        lo = parseInt(t, 16);
    }
    if (isNaN(hi)) { hi = 0; }
    if (isNaN(lo)) { lo = 0; }
    return hi * 4294967296 + lo;
}

/*
 * Known-negative control: the same enumeration over an address the caller
 * believes was never written.
 *
 * It is the same code path as the real query on purpose.  A control that used a
 * different mechanism would prove that the mechanism works, not that the query
 * does; the point of the negative is that the *same* query returns zero here and
 * non-zero there.
 *
 * An unmapped address is reported as UNMAPPED rather than as a zero.  The two are
 * different facts: "the trace shows no write here" is evidence, while "there is
 * no memory here to write" is not, and a control that conflated them would pass
 * for the wrong reason.
 */
function queryNegativeControl(address, maxHits) {
    var lo = _parseAddress(address);
    var result;
    try {
        result = _enumerate(lo, lo + 4, 'w', maxHits);
    } catch (err) {
        _log(PREFIX_CONTROL + '|negative_unmapped|' + _addr64(lo));
        return -1;
    }
    _log(PREFIX_CONTROL + '|negative_writes|' + result.hits.length);
    for (var i = 0; i < result.hits.length; i++) {
        var e = result.hits[i];
        _log(PREFIX_CONTROL + '|negative_hit|' + _addr64(e.Address) + '|'
             + _addr64(e.IP) + '|' + e.Size + '|' + e.ThreadId);
    }
    return result.hits.length;
}

/*
 * Sanity control that does not depend on the address being right: total writes
 * anywhere in the low 4 GB.
 *
 * A trace with zero events at all is a broken trace, not a clean one, and the
 * two look identical in a per-address query.  This distinguishes them.  The
 * bound is small because the answer only needs to be non-zero.
 */
function queryTraceIsLive(maxHits) {
    var result = _enumerate(0, 0x100000000, 'w', maxHits);
    _log(PREFIX_CONTROL + '|trace_live_writes|' + result.hits.length
         + '|truncated|' + (result.truncated ? 1 : 0));
    return result.hits.length;
}
