/* Generated by scripts/generate-lifter-tests.py. */
#include <stdint.h>
#include <stdio.h>
static uint32_t backing[64], eax,ebx,ecx,edx,esi,edi;
static int direction=1;
static unsigned flush_calls;
void recomp_guest_cache_flush(void) { ++flush_calls; }
#define MEM8(a) (((uint8_t*)backing)[(uint32_t)(a)])
#define MEM16(a) (*(uint16_t*)((uint8_t*)backing+(uint32_t)(a)))
#define MEM32(a) (*(uint32_t*)((uint8_t*)backing+(uint32_t)(a)))
#define memory MEM32(0)
#define XBOX_PTR(a) ((uint8_t*)backing+(uint32_t)(a))
#define RECOMP_DF_STEP(n) ((n)*direction)
#define TEST_Z(a,b) (((a)&(b))==0)
#define LO8(a) ((uint8_t)(a))
#define SET_LO8(a,b) ((a)=((a)&0xffffff00u)|(uint8_t)(b))
static uint32_t add32(uint32_t *p,uint32_t v) { uint32_t old=*p;*p+=v;return old; }
static uint32_t cas32(uint32_t *p,uint32_t c,uint32_t v) { uint32_t old=*p;if(old==c)*p=v;return old; }
#define RECOMP_ATOMIC_ADD32(p,v) add32((uint32_t*)(p),(v))
#define RECOMP_ATOMIC_CAS32(p,c,v) cas32((uint32_t*)(p),(c),(v))

static unsigned plain_xadd(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
{ uint32_t _add = edx;
  uint32_t _old = RECOMP_ATOMIC_ADD32(XBOX_PTR(ecx), _add);
  _fa = _old + _add; _fb = 0;
  _fas = (int32_t)_fa; _fbs = 0;
  edx = _old; }  /* xadd */
MEM32(ecx) = ebx;
SET_LO8(eax, ((_fa != 0)) ? 1 : 0); /* setne */
return LO8(eax);
}
static unsigned plain_cmpxchg(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
{ uint32_t _cmp = eax;
  uint32_t _old = RECOMP_ATOMIC_CAS32(XBOX_PTR(ecx), _cmp, edx);
  _fa = _old; _fb = _cmp;
  _fas = (int32_t)_fa; _fbs = (int32_t)_fb;
  if (_old != _cmp) eax = _old; }  /* cmpxchg */
MEM32(ecx) = ebx;
SET_LO8(eax, ((_fa != _fb)) ? 1 : 0); /* setne */
return LO8(eax);
}
static unsigned locked_xadd(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
{ uint32_t _add = edx;
  uint32_t _old = RECOMP_ATOMIC_ADD32(XBOX_PTR(ecx), _add);
  _fa = _old + _add; _fb = 0;
  _fas = (int32_t)_fa; _fbs = 0;
  edx = _old; }  /* lock xadd */
MEM32(ecx) = ebx;
SET_LO8(eax, ((_fa != 0)) ? 1 : 0); /* setne */
return LO8(eax);
}
static unsigned locked_cmpxchg(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
{ uint32_t _cmp = eax;
  uint32_t _old = RECOMP_ATOMIC_CAS32(XBOX_PTR(ecx), _cmp, edx);
  _fa = _old; _fb = _cmp;
  _fas = (int32_t)_fa; _fbs = (int32_t)_fb;
  if (_old != _cmp) eax = _old; }  /* lock cmpxchg */
MEM32(ecx) = ebx;
SET_LO8(eax, ((_fa != _fb)) ? 1 : 0); /* setne */
return LO8(eax);
}
static unsigned cmpsb(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
_fa = (uint32_t)(edx) & 0xFFFFFFFFu; _fb = (uint32_t)(edx) & 0xFFFFFFFFu;
_fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* test edx, edx (32-bit) */
eax = 0;
_flags = TEST_Z(_fa, _fb); /* zero-count REP preserves ZF */
{ int32_t _st = RECOMP_DF_STEP(1);
while (ecx != 0) {
    _flags = (MEM8(esi) == MEM8(edi));
    esi += _st; edi += _st; ecx--;
    if (!_flags) break;
} } /* repe cmpsb */
SET_LO8(eax, ((_flags != 0)) ? 1 : 0); /* sete */
return LO8(eax);
}
static unsigned cmpsw(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
_fa = (uint32_t)(edx) & 0xFFFFFFFFu; _fb = (uint32_t)(edx) & 0xFFFFFFFFu;
_fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* test edx, edx (32-bit) */
eax = 0;
_flags = TEST_Z(_fa, _fb); /* zero-count REP preserves ZF */
{ int32_t _st = RECOMP_DF_STEP(2);
while (ecx != 0) {
    _flags = (MEM16(esi) == MEM16(edi));
    esi += _st; edi += _st; ecx--;
    if (!_flags) break;
} } /* repe cmpsw */
SET_LO8(eax, ((_flags != 0)) ? 1 : 0); /* sete */
return LO8(eax);
}
static unsigned cmpsd(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
_fa = (uint32_t)(edx) & 0xFFFFFFFFu; _fb = (uint32_t)(edx) & 0xFFFFFFFFu;
_fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* test edx, edx (32-bit) */
eax = 0;
_flags = TEST_Z(_fa, _fb); /* zero-count REP preserves ZF */
{ int32_t _st = RECOMP_DF_STEP(4);
while (ecx != 0) {
    _flags = (MEM32(esi) == MEM32(edi));
    esi += _st; edi += _st; ecx--;
    if (!_flags) break;
} } /* repe cmpsd */
SET_LO8(eax, ((_flags != 0)) ? 1 : 0); /* sete */
return LO8(eax);
}
static unsigned cache_flush(void) {
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
_fa = (uint32_t)(edx) & 0xFFFFFFFFu; _fb = (uint32_t)(edx) & 0xFFFFFFFFu;
_fas = (int32_t)(int32_t)(_fa); _fbs = (int32_t)(int32_t)(_fb); /* test edx, edx (32-bit) */
{ extern void recomp_guest_cache_flush(void); recomp_guest_cache_flush(); } /* wbinvd */
SET_LO8(eax, (TEST_Z(_fa, _fb)) ? 1 : 0); /* sete */
return LO8(eax);
}

int main(void) {
    uint32_t old_values[]={0,1,2,0x7fffffff,0x80000000,0xffffffff};
    uint32_t adds[]={0,1,0xffffffff,0x80000000};
    uint32_t changes[]={0,1,0xdeadbeef};
    unsigned n=0;
    unsigned (*add_tests[])(void)={plain_xadd,locked_xadd};
    unsigned (*cas_tests[])(void)={plain_cmpxchg,locked_cmpxchg};
    for(unsigned t=0;t<2;t++) for(unsigned i=0;i<6;i++)
    for(unsigned j=0;j<4;j++) for(unsigned k=0;k<3;k++) {
        memory=old_values[i];edx=adds[j];ebx=changes[k];eax=0;ecx=0;
        unsigned expected=(uint32_t)(memory+edx)!=0;
        if(add_tests[t]()!=expected || edx!=old_values[i] || memory!=ebx) {
            fprintf(stderr,"XADD flags/old-value failure t=%u old=%X add=%X interference=%X\n",t,old_values[i],adds[j],ebx);return 1;
        }
        ++n;
        memory=old_values[i];eax=adds[j];edx=0x42;ebx=changes[k];ecx=0;
        expected=memory!=eax;
        if(cas_tests[t]()!=expected || memory!=ebx) {fprintf(stderr,"CMPXCHG flag failure\n");return 1;}
        ++n;
    }
    printf("PASS %u atomic result/flag cases, including intervening writes\n",n);
    unsigned (*comparisons[])(void)={cmpsb,cmpsw,cmpsd};
    unsigned sizes[]={1,2,4};
    n=0;
    for(unsigned t=0;t<3;t++) for(unsigned reverse=0;reverse<2;reverse++)
    for(unsigned count=0;count<=4;count++) for(unsigned mismatch=0;mismatch<5;mismatch++)
    for(unsigned incoming=0;incoming<2;incoming++) {
        unsigned width=sizes[t];
        for(unsigned b=0;b<16;b++) MEM8(32+b)=MEM8(64+b)=(uint8_t)(17+b);
        if(mismatch<4) MEM8(64+mismatch*width)^=0x80;
        direction=reverse?-1:1;esi=32+(reverse?3*width:0);edi=64+(reverse?3*width:0);
        uint32_t initial_si=esi,initial_di=edi;
        ecx=count;edx=incoming;
        unsigned matched=incoming==0,steps=0;
        for(unsigned i=0;i<count;i++) {
            unsigned at=reverse?3-i:i;
            matched=mismatch!=at;++steps;if(!matched) break;
        }
        unsigned result=comparisons[t]();
        if(result!=matched || ecx!=count-steps || esi!=initial_si+direction*steps*width || edi!=initial_di+direction*steps*width) {
            fprintf(stderr,"CMPS flags/iteration failure width=%u reverse=%u count=%u mismatch=%u incoming=%u\n",width,reverse,count,mismatch,incoming);return 1;
        }
        ++n;
    }
    printf("PASS %u string comparison/flag/direction/zero-count cases\n",n);
    for(unsigned initial=0;initial<2;initial++) {
        edx=initial;flush_calls=0;
        if(cache_flush()!=(initial==0) || flush_calls!=1) {
            fprintf(stderr,"WBINVD helper/flag preservation failure\n");return 1;
        }
    }
    puts("PASS WBINVD lowering calls ordering helper and preserves flags");
    return 0;
}
