"""Generate a va -> expected-ESP-delta table for the ABI check.

Why: RECOMP_ABI_CALL's `g_esp < _ap + 4` is a deliberate lower bound, so a callee
that returns with ESP too HIGH passes silently. That is exactly how a 4-byte
over-pop in 0x001690A0 propagated into a wrong g_esi, a wrong eax, a wrong store
into the game's central object, and a call to NULL.

Recovered entries are already checked exactly by their own wrapper. The gap is the
*generated* functions, which have no wrapper. Their expected delta is in their own
body: `esp += N; return;`. A body with several distinct exits is ambiguous, so all
observed values are accepted.

Emits src/recomp/gen/recomp_abi_deltas.c and declares the entry point.
"""
import glob
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
chunks = sorted(glob.glob(str(root / "src/recomp/gen/recomp_0*.c")))

# Addresses whose ESP delta is legitimately whatever they like, and which the
# register-preservation check must also skip. Checked first, so their constant
# traffic cannot crowd out a real finding.
#
# Two distinct reasons, both verified against the guest code:
#
#  * The SEH pair. __SEH_prolog (0x17D1F8) pushes ebx/esi/edi and __SEH_epilog
#    (0x17D231) pops them. __SEH_epilog is entered by TAIL JUMP and its whole
#    purpose is to change those three registers, so a before/after comparison
#    across a call to it must differ. Flagging it is meaningless.
#  * The integer runtime helpers. MSVC's 64-bit divide/multiply helpers use EBX as
#    scratch and deliberately do not preserve it; they are only ever called from
#    compiler-generated code, which keeps nothing live in EBX across the call.
#    0x001816B0 is the 64-bit unsigned divide (7 div/mul, `mov ebx, eax` between
#    two `div`s). The other four open with `push <frame>; push <scopetable>;
#    call __SEH_prolog`, so they use EBX as a SEH frame register, and the prolog
#    and epilog are what save and restore it -- the body's own EBX writes are not
#    a clobber.
EXEMPT = {
    0x0017D1F8: "SEH __SEH_prolog; adjusts the stack and the caller's frame itself",
    0x0017D231: "SEH __SEH_epilog; tail-jumped, and its job is to change ebx/esi/edi",
    0x001816B0: "64-bit integer divide helper; uses ebx as scratch, never preserves it",
    0x00180EC0: "SEH function; ebx is the frame register, saved by __SEH_prolog",
    0x00149F5E: "SEH function; ebx is the frame register, saved by __SEH_prolog",
    0x00147EBB: "SEH function; ebx is the frame register, saved by __SEH_prolog",
    0x00148164: "SEH function; ebx is the frame register, saved by __SEH_prolog",
}

deltas = {}
for path in chunks:
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    for m in re.finditer(r"^void (sub_[0-9A-F]{8})\(void\)$", text, re.M):
        name = m.group(1)
        nxt = text.find("\nvoid sub_", m.end())
        body = text[m.end(): nxt if nxt != -1 else len(text)]
        vals = sorted({int(v) for v in re.findall(r"esp \+= (\d+); return;", body)})
        if vals:
            deltas[int(name[4:], 16)] = vals[:4]

print("generated functions with a known delta:", len(deltas))
ambiguous = sum(1 for v in deltas.values() if len(v) > 1)
print("  of which with several distinct exits:", ambiguous)

out = root / "src/recomp/gen/recomp_abi_deltas.c"
lines = [
    "/* Generated by scripts/gen-abi-deltas.py -- expected ESP delta per generated",
    " * function, for the exact ABI check. See that script for why. */",
    "#define RECOMP_GENERATED_CODE",
    '#include "../gen/recomp_types.h"',
    "",
    "typedef struct { uint32_t va; uint32_t d[4]; } RecompDeltaEntry;",
    "",
    "static const RecompDeltaEntry g_recomp_deltas[] = {",
]
for va in sorted(deltas):
    ds = deltas[va]
    padded = (ds + [0, 0, 0, 0])[:4]
    lines.append("    { 0x%08Xu, { %s } }," % (va, ", ".join("%du" % d for d in padded)))
lines += [
    "};",
    "",
    "/* Addresses exempt from BOTH the delta check and the register check, checked",
    " * first so their constant traffic cannot crowd out a real finding. The",
    " * generator script records why each one is here. */",
    "static const uint32_t g_recomp_abi_exempt[] = {",
]
for va in sorted(EXEMPT):
    lines.append("    0x%08Xu, /* %s */" % (va, EXEMPT[va]))
lines += [
    "};",
    "",
    "static int recomp_va_exempt(uint32_t va)",
    "{",
    "    size_t i;",
    "    for (i = 0; i < sizeof(g_recomp_abi_exempt) / sizeof(g_recomp_abi_exempt[0]); i++)",
    "        if (g_recomp_abi_exempt[i] == va) return 1;",
    "    return 0;",
    "}",
    "",
    "/* 1 = skip the ebx/esi/edi preservation check for this address. The SEH epilog",
    " * and the integer helpers change those registers by design, so comparing them",
    " * before and after the call reports a difference that is not a defect. */",
    "int recomp_abi_regs_exempt(uint32_t va)",
    "{",
    "    return recomp_va_exempt(va);",
    "}",
    "",
    "/* 1 = the observed delta is one this function can produce, the address is exempt,",
    " * or the address is unknown to this table. 0 = it cannot, which means a caller's",
    " * frame is about to be read at the wrong offsets. Binary search: this runs on",
    " * every call. */",
    "int recomp_delta_ok(uint32_t va, uint32_t actual)",
    "{",
    "    size_t lo = 0, hi = sizeof(g_recomp_deltas) / sizeof(g_recomp_deltas[0]);",
    "    if (recomp_va_exempt(va)) return 1;",
    "    while (lo < hi) {",
    "        size_t mid = lo + (hi - lo) / 2;",
    "        const RecompDeltaEntry *e = &g_recomp_deltas[mid];",
    "        if (e->va == va)",
    "            return e->d[0] == actual || e->d[1] == actual ||",
    "                   e->d[2] == actual || e->d[3] == actual;",
    "        if (e->va < va) lo = mid + 1; else hi = mid;",
    "    }",
    "    return 1;",
    "}",
    "",
    "/* Diagnostic only: fills out[] with the deltas this table allows for va and",
    " * returns how many. 0 means the address is not in the table, which is unknown",
    " * rather than a mismatch. Used to print the expected value next to the observed",
    " * one, so a report says what the 4 bytes should have been. */",
    "int recomp_delta_allowed(uint32_t va, uint32_t out[4])",
    "{",
    "    size_t lo = 0, hi = sizeof(g_recomp_deltas) / sizeof(g_recomp_deltas[0]);",
    "    int n = 0, i;",
    "    if (recomp_va_exempt(va)) return 0;",
    "    while (lo < hi) {",
    "        size_t mid = lo + (hi - lo) / 2;",
    "        const RecompDeltaEntry *e = &g_recomp_deltas[mid];",
    "        if (e->va == va) {",
    "            for (i = 0; i < 4; i++) if (e->d[i]) out[n++] = e->d[i];",
    "            return n;",
    "        }",
    "        if (e->va < va) lo = mid + 1; else hi = mid;",
    "    }",
    "    return 0;",
    "}",
]
out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print("wrote", out)
