"""Generate a va -> expected-ESP-delta table for the ABI check.

Why: RECOMP_ABI_CALL's `g_esp < _ap + 4` is a deliberate lower bound, so a callee
that returns with ESP too HIGH passes silently. That is exactly how a 4-byte
over-pop in 0x001690A0 propagated into a wrong g_esi, a wrong eax, a wrong store
into the game's central object, and a call to NULL.

Recovered entries are already checked exactly by their own wrapper. The gap is the
*generated* functions, which have no wrapper. Their expected delta is in their own
body: `esp += N; return;`. A body with several distinct exits is ambiguous, so all
observed values are accepted.

Emits src/recomp/gen/recomp_abi_deltas.c and declares the entry point.
"""
import glob
import re
from pathlib import Path

root = Path(r"C:\Users\logic\Repos\my_xbox_game")
chunks = sorted(glob.glob(str(root / "src/recomp/gen/recomp_0*.c")))

# The Windows SEH helpers adjust the stack themselves by design, so their delta is
# whatever the exception path needs. They fire constantly, and a first version of
# the check let them exhaust its cap -- which is how a real mismatch in
# sub_001680D0 went unreported. Exempt them so the signal is not drowned.
EXEMPT = {
    0x0017D1F8: "SEH __SEH_prolog-style helper; adjusts the stack itself",
    0x0017D231: "SEH helper; adjusts the stack itself",
}

deltas = {}
for path in chunks:
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    for m in re.finditer(r"^void (sub_[0-9A-F]{8})\(void\)$", text, re.M):
        name = m.group(1)
        nxt = text.find("\nvoid sub_", m.end())
        body = text[m.end(): nxt if nxt != -1 else len(text)]
        vals = sorted({int(v) for v in re.findall(r"esp \+= (\d+); return;", body)})
        if vals:
            deltas[int(name[4:], 16)] = vals[:4]

print("generated functions with a known delta:", len(deltas))
ambiguous = sum(1 for v in deltas.values() if len(v) > 1)
print("  of which with several distinct exits:", ambiguous)

out = root / "src/recomp/gen/recomp_abi_deltas.c"
lines = [
    "/* Generated by scripts/gen-abi-deltas.py -- expected ESP delta per generated",
    " * function, for the exact ABI check. See that script for why. */",
    "#define RECOMP_GENERATED_CODE",
    '#include "../gen/recomp_types.h"',
    "",
    "typedef struct { uint32_t va; uint32_t d[4]; } RecompDeltaEntry;",
    "",
    "static const RecompDeltaEntry g_recomp_deltas[] = {",
]
for va in sorted(deltas):
    ds = deltas[va]
    padded = (ds + [0, 0, 0, 0])[:4]
    lines.append("    { 0x%08Xu, { %s } }," % (va, ", ".join("%du" % d for d in padded)))
lines += [
    "};",
    "",
    "/* Addresses whose ESP delta is legitimately whatever they like. Checked first so",
    " * their constant traffic cannot crowd out a real mismatch. */",
    "static const uint32_t g_recomp_delta_exempt[] = {",
]
for va in sorted(EXEMPT):
    lines.append("    0x%08Xu, /* %s */" % (va, EXEMPT[va]))
lines += [
    "};",
    "",
    "/* 1 = the observed delta is one this function can produce, the address is exempt,",
    " * or the address is unknown to this table. 0 = it cannot, which means a caller's",
    " * frame is about to be read at the wrong offsets. Binary search: this runs on",
    " * every call. */",
    "int recomp_delta_ok(uint32_t va, uint32_t actual)",
    "{",
    "    size_t lo = 0, hi = sizeof(g_recomp_deltas) / sizeof(g_recomp_deltas[0]);",
    "    size_t i;",
    "    for (i = 0; i < sizeof(g_recomp_delta_exempt) / sizeof(g_recomp_delta_exempt[0]); i++)",
    "        if (g_recomp_delta_exempt[i] == va) return 1;",
    "    while (lo < hi) {",
    "        size_t mid = lo + (hi - lo) / 2;",
    "        const RecompDeltaEntry *e = &g_recomp_deltas[mid];",
    "        if (e->va == va)",
    "            return e->d[0] == actual || e->d[1] == actual ||",
    "                   e->d[2] == actual || e->d[3] == actual;",
    "        if (e->va < va) lo = mid + 1; else hi = mid;",
    "    }",
    "    return 1;",
    "}",
]
out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print("wrote", out)
