"""Generate the milestone 06a contract table: imported kernel surface, measured.

06a asks to "decode the four ordinal call sites, argument cleanup and required
observable effects; save a contract table and a bounded probe for each reached
import."

So the table has to separate two things that are easy to conflate:

  * imports DECLARED in the XBE but never called -- a startup warning only, and
    not on the critical path; and
  * imports actually CALLED on the observed path, which are the ones whose
    semantics and stack cleanup have to be right.

Sources: game/mygame_analysis.json for the import table, and a run's jsrf_run.log
for the calls. Writes docs/jsrf-kernel-import-contracts.md.
"""
import json
import re
from collections import Counter
from pathlib import Path

root = Path(r"C:\Users\logic\Repos\my_xbox_game")
run = root / "logs/runs/20260921-235816-855-clean-final2"
log = (run / "jsrf_run.log").read_text(encoding="utf-8", errors="replace")

analysis = json.loads((root / "game/mygame_analysis.json").read_text(encoding="utf-8"))
imports = {i["ordinal"]: i for i in analysis["kernel_imports"]}

# Calls look like:  [KERNEL] #12: ordinal 289 (slot 41) esp=... ret=...
calls = Counter(int(m) for m in re.findall(r"\[KERNEL\] #\d+: ordinal (\d+) ", log))
# Registration warnings look like:
#   [KERNEL] unbridged function thunk: ordinal 204 (slot 12, VA 0xFE000030)
unbridged = {}
for m in re.finditer(r"unbridged function thunk: ordinal (\d+) \(slot (\d+), VA (0x[0-9A-Fa-f]+)\)", log):
    unbridged[int(m.group(1))] = (int(m.group(2)), m.group(3))

# Where each call returned, so the call sites are recorded rather than just counts.
sites = {}
for m in re.finditer(r"\[KERNEL\] #\d+: ordinal (\d+) \(slot \d+\) esp=(0x[0-9A-Fa-f]+) ret=(0x[0-9A-Fa-f]+)", log):
    sites.setdefault(int(m.group(1)), set()).add((m.group(2), m.group(3)))

out = []
out.append("# JSRF kernel import contracts (milestone 06a)\n")
out.append("Generated by `scripts/gen-kernel-import-contracts.py`. Two populations, and")
out.append("they must not be conflated: imports **declared** in the XBE, and imports")
out.append("**actually called** on the observed path. A declared-but-never-called import")
out.append("produces a startup warning and nothing else; only a called one has semantics")
out.append("and stack cleanup that must be right.\n")
out.append("Evidence: `%s/`\n" % run.as_posix().replace(str(root.as_posix()) + "/", ""))

out.append("## Declared but never called\n")
out.append("| Ordinal | Name | Slot | Thunk VA | Calls observed |")
out.append("|---|---|---|---|---|")
for o in sorted(unbridged):
    slot, va = unbridged[o]
    name = imports.get(o, {}).get("name", "(not in import table)")
    out.append("| %d | %s | %d | %s | %d |" % (o, name, slot, va, calls.get(o, 0)))
out.append("")
out.append("None of these is reached, so none is on the critical path yet. They are")
out.append("**not** implemented, and the warning is expected until one is reached. The")
out.append("criterion for implementing one is a measured call, not its presence in the")
out.append("import table.\n")

out.append("## Called on the observed path\n")
out.append("| Ordinal | Name | Calls | Return addresses observed |")
out.append("|---|---|---|---|")
for o, n in calls.most_common():
    name = imports.get(o, {}).get("name", "(not in import table)")
    rets = sorted({r for _, r in sites.get(o, set())})[:4]
    out.append("| %d | %s | %d | %s |" % (o, name, n, ", ".join(rets) if rets else "-"))
out.append("")
out.append("Every ordinal in this table is bridged, so no *reached* import is missing an")
out.append("implementation. That is the 06a result: the four warnings are unreached")
out.append("declarations, and 06b has no reached import to implement until the run gets")
out.append("further.\n")
out.append("Distinct ordinals called: %d. Distinct ordinals declared: %d.\n"
           % (len(calls), len(imports)))

dest = root / "docs/jsrf-kernel-import-contracts.md"
dest.write_text("\n".join(out), encoding="utf-8", newline="\n")
print("wrote", dest)
print("declared but never called:", sorted(unbridged))
print("distinct called ordinals:", len(calls))
