"""Generate executable instruction regressions from actual x86 bytes."""
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root.parent/'xboxrecomp'))
from tools.recomp.disasm import Disassembler, BasicBlock
from tools.recomp.lifter import Lifter,lift_basic_block

parts=[r'''/* Generated by scripts/generate-lifter-tests.py. */
#include <stdint.h>
#include <stdio.h>
static uint32_t backing[64], eax,ebx,ecx,edx,esi,edi;
static int direction=1;
static unsigned flush_calls;
void recomp_guest_cache_flush(void) { ++flush_calls; }
#define MEM8(a) (((uint8_t*)backing)[(uint32_t)(a)])
#define MEM16(a) (*(uint16_t*)((uint8_t*)backing+(uint32_t)(a)))
#define MEM32(a) (*(uint32_t*)((uint8_t*)backing+(uint32_t)(a)))
#define memory MEM32(0)
#define XBOX_PTR(a) ((uint8_t*)backing+(uint32_t)(a))
#define RECOMP_DF_STEP(n) ((n)*direction)
#define TEST_Z(a,b) (((a)&(b))==0)
#define LO8(a) ((uint8_t)(a))
#define SET_LO8(a,b) ((a)=((a)&0xffffff00u)|(uint8_t)(b))
static uint32_t add32(uint32_t *p,uint32_t v) { uint32_t old=*p;*p+=v;return old; }
static uint32_t cas32(uint32_t *p,uint32_t c,uint32_t v) { uint32_t old=*p;if(old==c)*p=v;return old; }
#define RECOMP_ATOMIC_ADD32(p,v) add32((uint32_t*)(p),(v))
#define RECOMP_ATOMIC_CAS32(p,c,v) cas32((uint32_t*)(p),(c),(v))
''']
# MOV simulates a different thread changing the shared destination after the
# atomic operation; it must not change this thread's arithmetic flags.
for prefix,name in [('', 'plain'),('f0','locked')]:
    for opcode,op in [('0fc111','xadd'),('0fb111','cmpxchg')]:
        raw=bytes.fromhex(prefix+opcode+'8919'+'0f95c0')
        ins=Disassembler().disassemble_function(raw,0,len(raw))
        code,_=lift_basic_block(Lifter(),BasicBlock(start=0,instructions=ins))
        parts.append(f'''static unsigned {name}_{op}(void) {{
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
{chr(10).join(code)}
return LO8(eax);
}}''')
for name,raw_hex in [('cmpsb','85d2b800000000f3a60f94c0'),
                     ('cmpsw','85d2b800000000f366a70f94c0'),
                     ('cmpsd','85d2b800000000f3a70f94c0'),
                     ('cache_flush','85d20f090f94c0')]:
    raw=bytes.fromhex(raw_hex)
    ins=Disassembler().disassemble_function(raw,0,len(raw))
    code,_=lift_basic_block(Lifter(),BasicBlock(start=0,instructions=ins))
    parts.append(f'''static unsigned {name}(void) {{
int _flags=0; uint32_t _fa=0,_fb=0; int32_t _fas=0,_fbs=0;
{chr(10).join(code)}
return LO8(eax);
}}''')
parts.append(r'''
int main(void) {
    uint32_t old_values[]={0,1,2,0x7fffffff,0x80000000,0xffffffff};
    uint32_t adds[]={0,1,0xffffffff,0x80000000};
    uint32_t changes[]={0,1,0xdeadbeef};
    unsigned n=0;
    unsigned (*add_tests[])(void)={plain_xadd,locked_xadd};
    unsigned (*cas_tests[])(void)={plain_cmpxchg,locked_cmpxchg};
    for(unsigned t=0;t<2;t++) for(unsigned i=0;i<6;i++)
    for(unsigned j=0;j<4;j++) for(unsigned k=0;k<3;k++) {
        memory=old_values[i];edx=adds[j];ebx=changes[k];eax=0;ecx=0;
        unsigned expected=(uint32_t)(memory+edx)!=0;
        if(add_tests[t]()!=expected || edx!=old_values[i] || memory!=ebx) {
            fprintf(stderr,"XADD flags/old-value failure t=%u old=%X add=%X interference=%X\n",t,old_values[i],adds[j],ebx);return 1;
        }
        ++n;
        memory=old_values[i];eax=adds[j];edx=0x42;ebx=changes[k];ecx=0;
        expected=memory!=eax;
        if(cas_tests[t]()!=expected || memory!=ebx) {fprintf(stderr,"CMPXCHG flag failure\n");return 1;}
        ++n;
    }
    printf("PASS %u atomic result/flag cases, including intervening writes\n",n);
    unsigned (*comparisons[])(void)={cmpsb,cmpsw,cmpsd};
    unsigned sizes[]={1,2,4};
    n=0;
    for(unsigned t=0;t<3;t++) for(unsigned reverse=0;reverse<2;reverse++)
    for(unsigned count=0;count<=4;count++) for(unsigned mismatch=0;mismatch<5;mismatch++)
    for(unsigned incoming=0;incoming<2;incoming++) {
        unsigned width=sizes[t];
        for(unsigned b=0;b<16;b++) MEM8(32+b)=MEM8(64+b)=(uint8_t)(17+b);
        if(mismatch<4) MEM8(64+mismatch*width)^=0x80;
        direction=reverse?-1:1;esi=32+(reverse?3*width:0);edi=64+(reverse?3*width:0);
        uint32_t initial_si=esi,initial_di=edi;
        ecx=count;edx=incoming;
        unsigned matched=incoming==0,steps=0;
        for(unsigned i=0;i<count;i++) {
            unsigned at=reverse?3-i:i;
            matched=mismatch!=at;++steps;if(!matched) break;
        }
        unsigned result=comparisons[t]();
        if(result!=matched || ecx!=count-steps || esi!=initial_si+direction*steps*width || edi!=initial_di+direction*steps*width) {
            fprintf(stderr,"CMPS flags/iteration failure width=%u reverse=%u count=%u mismatch=%u incoming=%u\n",width,reverse,count,mismatch,incoming);return 1;
        }
        ++n;
    }
    printf("PASS %u string comparison/flag/direction/zero-count cases\n",n);
    for(unsigned initial=0;initial<2;initial++) {
        edx=initial;flush_calls=0;
        if(cache_flush()!=(initial==0) || flush_calls!=1) {
            fprintf(stderr,"WBINVD helper/flag preservation failure\n");return 1;
        }
    }
    puts("PASS WBINVD lowering calls ordering helper and preserves flags");
    return 0;
}
''')
(root/'tests/lifter-regressions.c').write_text('\n'.join(parts),encoding='utf-8')
