"""Measure what is reclaimable in logs/ WITHOUT deleting durable evidence.

The disk is full, and the mandated harness verification cannot run. Before proposing any
deletion, this classifies every run directory so the reclamation can be scoped to
regenerable scratch only.

Classification:
  * save-root/  -- the emulated-disk partition images. Recreated from scratch on every
                   run; the runner copies them in per run. They are the bulk.
  * everything else in a run dir -- stacks.txt, jsrf_run.log, result.json, metadata,
                   dumps, maps. These ARE the evidence a record cites.

Run naming:
  * test-*  -- harness probes; regenerated by re-running the harness.
  * other   -- named evidence runs; a record may cite these by directory name.

Sparse-aware: uses GetCompressedFileSizeW so a 2.36 GB sparse Partition1.img reports
its real cost, not its logical size.
"""
import ctypes
import sys
from collections import defaultdict
from ctypes import wintypes
from pathlib import Path

kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
_Get = kernel32.GetCompressedFileSizeW
_Get.argtypes = [wintypes.LPCWSTR, ctypes.POINTER(wintypes.DWORD)]
_Get.restype = wintypes.DWORD
INVALID = 0xFFFFFFFF


def alloc(p: Path) -> int:
    hi = wintypes.DWORD(0)
    lo = _Get(str(p), ctypes.byref(hi))
    if lo == INVALID and ctypes.get_last_error() != 0:
        try:
            return p.stat().st_size
        except OSError:
            return 0
    return (hi.value << 32) | lo


ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("logs/runs")

buckets = defaultdict(lambda: [0, 0])  # name -> [files, bytes]
save_root_total = 0
save_root_files = 0
by_run_kind = defaultdict(lambda: [0, 0])

for run in sorted(ROOT.iterdir()):
    if not run.is_dir():
        continue
    kind = "test" if run.name.split("-", 3)[-1].startswith("test-") else "named"
    for p in run.rglob("*"):
        try:
            if not p.is_file():
                continue
        except OSError:
            continue
        a = alloc(p)
        rel = p.relative_to(run)
        if rel.parts and rel.parts[0] == "save-root":
            save_root_total += a
            save_root_files += 1
            by_run_kind[kind + ":save-root"][0] += 1
            by_run_kind[kind + ":save-root"][1] += a
        else:
            by_run_kind[kind + ":evidence"][0] += 1
            by_run_kind[kind + ":evidence"][1] += a

print("  root: %s" % ROOT)
print()
print("  %-28s %10s %14s" % ("bucket", "files", "GB"))
for k in sorted(by_run_kind):
    f, b = by_run_kind[k]
    print("  %-28s %10d %14.2f" % (k, f, b / 1024**3))
print()
print("  save-root TOTAL: %d files, %.2f GB" % (save_root_files, save_root_total / 1024**3))
