"""Lift only reviewed entries; keep the original database and generated splits intact."""
from pathlib import Path
import hashlib
import json
import re
import sys

root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root.parent/'xboxrecomp'))
from tools.recomp import config
from tools.recomp.translator import FunctionTranslator

xbe=root/'game/default.xbe'
data=xbe.read_bytes()
assert hashlib.sha256(data).hexdigest().upper()=='FD19055756719893C466302809B433B785ECF5732DF0441286F3F605F0F3EF9C', 'Review recovery addresses for this XBE first'
config.configure_from_xbe(str(xbe))
entries=json.loads((root/'config/recovered-functions.json').read_text())
database={}
for item in json.loads((root/'tools/disasm/output/functions.json').read_text()):
    address=int(item['start'],16)
    item['_addr']=address;item['end']=int(item['end'],16)
    database[address]=item
for fix in json.loads((root/'config/boundary-fixes.json').read_text(encoding='utf-8')):
    address=int(fix['start'],16);database[address]['end']=int(fix['end'],16)
    database[address]['size']=database[address]['end']-address
# Raw analysis predates the installed CRT names. Preserve actual symbols.
for existing in (root/'src/recomp/gen').glob('recomp_*.c'):
    for m in re.finditer(r'Original: 0x([0-9A-F]+)(?:(?!\*/).)*\*/\nvoid (\w+)\(void\)',existing.read_text(encoding='utf-8'),re.S):
        if int(m[1],16) in database:database[int(m[1],16)]['name']=m[2]
for entry in entries:
    address=int(entry['start'],16);end=int(entry['end'],16)
    database[address]={**entry,'_addr':address,'end':end,'size':end-address,
        'name':f'sub_{address:08X}','confidence':1.0,'detection_method':'reviewed_runtime_target',
        'has_prologue':False,'calls_to':[],'called_by':[]}
labels={int(v['address'],16):v['name'] for v in json.loads((root/'tools/disasm/output/labels.json').read_text())}
translator=FunctionTranslator(data,database,labels)
source_header=['/* Generated by scripts/recover-functions.py; reviewed boundaries in config/recovered-functions.json. */',
        '#define RECOMP_GENERATED_CODE', '#include "../gen/recomp_types.h"',
        '#include <stdio.h>', '#include <stdlib.h>',
        'extern void xbox_outb(uint16_t port, uint8_t value);',
        'extern void xbox_outw(uint16_t port, uint16_t value);',
        'extern void xbox_outl(uint16_t port, uint32_t value);',
        'extern uint8_t xbox_inb(uint16_t port);',
        'extern uint16_t xbox_inw(uint16_t port);',
        'extern uint32_t xbox_inl(uint16_t port);']
declaration_names=set(translator.lifter.referenced_calls.values())
rendered={}
for entry in entries:
    address=int(entry['start'],16)
    code=translator.translate_function(address,database[address])
    if not code or '/* TODO:' in code: raise RuntimeError(f'Incomplete translation at {address:08X}')
    declaration_names.update(re.findall(r'\bsub_[0-9A-Fa-f]{8}\b', code))
    # The x86 IMUL destination is the low 32 bits of the product.  The
    # translator's signed C expression has undefined behavior on overflow;
    # preserve the guest operation with widened unsigned arithmetic before
    # the existing unsigned DIV sequence.  Keep this correction in the
    # generator so production and focused fixtures cannot diverge.
    if address == 0x00196800:
        code=code.replace(
            'eax = (uint32_t)((int32_t)eax * (int32_t)ecx);',
            'eax = (uint32_t)((uint64_t)(uint32_t)eax * (uint64_t)(uint32_t)ecx);')
        code=code.replace(
            'eax = (uint32_t)((int32_t)eax * (int32_t)edi);',
            'eax = (uint32_t)((uint64_t)(uint32_t)eax * (uint64_t)(uint32_t)edi);')
    if address == 0x00194210:
        # Production and focused fixtures both treat this INT3 as fatal.
        code=code.replace('/* int3: debug-trap slide byte, stepped over */',
                          'recomp_icall_fail_log(0x001942DFu); abort(); /* original INT3 */')
    if address == 0x00196C83:
        # x86 variable shifts use the low five bits of CL.  Keep the
        # raw-requested-channel path defined in host C for arg==32 while
        # retaining the original unmasked (arg << 6) slot address below.
        code=code.replace('edx = edx << LO8(ecx);',
                          'edx = edx << (LO8(ecx) & 31u);')
    # Public symbol is the checked wrapper, so direct calls are checked too.
    code=code.replace(f'void sub_{address:08X}(void)',f'static void body_{address:08X}(void)',1)
    stack_delta=4+entry.get('stack_args',0)
    restore_frame=entry.get('restore_frame_metadata',False)
    frame_check=' || g_ebp!=before_bp' if entry.get('kind','initializer')=='initializer' and not restore_frame else ''
    frame_save=', before_seh=g_seh_ebp' if restore_frame else ''
    frame_restore='\n    g_ebp=before_bp; g_seh_ebp=before_seh;' if restore_frame else ''
    wrapper=f'''void sub_{address:08X}(void) {{
    uint32_t before_stack=g_esp, before_bx=g_ebx, before_si=g_esi, before_di=g_edi, before_bp=g_ebp{frame_save};
    static RECOMP_TLS int logged;
    body_{address:08X}();{frame_restore}
    if (g_esp!=before_stack+{stack_delta} || g_ebx!=before_bx || g_esi!=before_si || g_edi!=before_di{frame_check}) {{
        fprintf(stderr,"[RECOVERED] ABI FAILURE 0x{address:08X} esp %08X->%08X expected +{stack_delta}; bx %08X->%08X si %08X->%08X di %08X->%08X bp %08X->%08X\\n",before_stack,g_esp,before_bx,g_ebx,before_si,g_esi,before_di,g_edi,before_bp,g_ebp); abort();
    }}
    if (!logged++) fprintf(stderr,"[RECOVERED] 0x{address:08X} returned; ABI verified (ESP/EBX/ESI/EDI)\\n");
}}'''
    rendered[address]=(code,wrapper)
declarations='\n'.join(f'extern void {name}(void);' for name in sorted(declaration_names))
chunks=source_header.copy()
for entry in entries:
    chunks.extend(rendered[int(entry['start'],16)])
chunks+=['recomp_func_t jsrf_lookup_recovered(uint32_t va) {','    switch (va) {']
for entry in entries:
    address=int(entry['start'],16)
    chunks.append(f'    case 0x{address:08X}u: return sub_{address:08X};')
chunks+=['    default: return 0;','    }','}']
output=root/'src/recomp/recovered/recovered.c';output.parent.mkdir(parents=True,exist_ok=True)
chunks.insert(5,declarations)
output.write_text('\n\n'.join(chunks)+'\n',encoding='utf-8')
# Focused recovery tests compile only their manifest-selected entries. The body
# and checked wrapper strings are the same objects emitted into recovered.c, so
# tests cannot drift into handwritten copies or pull unrelated dependencies.
test_units={}
for entry in entries:
    unit=entry.get('test_unit')
    if not unit: continue
    if not re.fullmatch(r'[a-z0-9_]+',unit):
        raise RuntimeError(f'Invalid recovery test unit {unit!r}')
    test_units.setdefault(unit,[]).append(int(entry['start'],16))
for unit,addresses in test_units.items():
    unit_chunks=source_header.copy()
    for address in addresses:
        code, wrapper = rendered[address]
        if address == 0x00196C0B:
            # Keep production direct calls bound to fatal unresolved symbols.
            # Only the focused fixture gets counted callback seams.
            code=code.replace('RECOMP_ABI_CALL(0x00194210u, sub_00194210)',
                              'RECOMP_ABI_CALL(0x00194210u, jsrf_test_service_194210)')
            code=code.replace('RECOMP_ABI_CALL(0x00193D90u, sub_00193D90)',
                              'RECOMP_ABI_CALL(0x00193D90u, jsrf_test_service_193D90)')
        if address == 0x00193D10:
            # Focused tests observe both original hardware helper calls while
            # production remains bound to the fatal unresolved symbols.
            code=code.replace('RECOMP_ABI_CALL(0x0018E500u, sub_0018E500)',
                              'RECOMP_ABI_CALL(0x0018E500u, jsrf_test_submit_18E500)')
            code=code.replace('RECOMP_ABI_CALL(0x0018E584u, sub_0018E584)',
                              'RECOMP_ABI_CALL(0x0018E584u, jsrf_test_submit_18E584)')
        if address == 0x00194210:
            # Focused tests model W1C readback by clearing INTR in the callee.
            code=code.replace('RECOMP_ABI_CALL(0x00197AACu, sub_00197AAC)',
                              'RECOMP_ABI_CALL(0x00197AACu, jsrf_test_97AAC)')
        if address == 0x00197AAC:
            code=code.replace('RECOMP_ABI_CALL(0x00196C4Au, sub_00196C4A)',
                              'RECOMP_ABI_CALL(0x00196C4Au, jsrf_test_96C4A)')
            code=code.replace('RECOMP_ABI_CALL(0x00194210u, sub_00194210)',
                              'RECOMP_ABI_CALL(0x00194210u, jsrf_test_194210_reentry)')
        if address == 0x00194780:
            code=code.replace('RECOMP_ABI_CALL(0x00197C50u, sub_00197C50)',
                              'RECOMP_ABI_CALL(0x00197C50u, jsrf_test_97C50)')
        unit_chunks.extend((code, wrapper))
    unit_declarations=declarations
    if 0x00196C0B in addresses:
        unit_declarations += '\nextern void jsrf_test_service_194210(void);\nextern void jsrf_test_service_193D90(void);'
    if 0x00193D10 in addresses:
        unit_declarations += '\nextern void jsrf_test_submit_18E500(void);\nextern void jsrf_test_submit_18E584(void);'
    if 0x00194210 in addresses:
        unit_declarations += '\nextern void jsrf_test_97AAC(void);'
    if 0x00197AAC in addresses:
        unit_declarations += '\nextern void jsrf_test_96C4A(void);\nextern void jsrf_test_194210_reentry(void);'
    if 0x00194780 in addresses:
        unit_declarations += '\nextern void jsrf_test_97C50(void);'
    unit_chunks.insert(5,unit_declarations)
    unit_output=output.parent/f'recovered_{unit}_test.c'
    unit_output.write_text('\n\n'.join(unit_chunks)+'\n',encoding='utf-8')
# This script does NOT own src/recomp/gen/recomp_stubs_unresolved.c.
#
# That file, recomp_funcs.h, the recomp_NNNN.c chunks and the dispatch table are
# all written by one full translate_batch_split pass over the whole function
# database (tools/recomp/translator.py:1283). This script translates only the
# reviewed entries, so its lifter sees a handful of referenced calls where the
# full pass saw 541 -- and it used to strip every stub body from that file and
# refill it from its own tiny view.
#
# The result was a split generated tree: the header declared 541 unresolved
# stubs while the file that defines them held 3, and the link failed with
# LNK1120: 473 unresolved externals pointing at correct generated code. The 16
# identical orphan comments that accumulated in the stub file -- one per run, no
# bodies after any of them -- were the fossil of that clobbering.
#
# So the traps this script needs go to its own file, and the translator's stub
# file is left exactly as the full pass wrote it. Nothing here deletes a
# definition it did not create.
#
# Newly exposed direct calls must be linkable and fail visibly until reviewed.
# These are diagnostic traps, with no guessed stack cleanup or success return.
# Only the production tree may suppress a trap: focused fixtures deliberately
# hand-write counted seams for the same addresses (see tests/test_recovery_*.c),
# so scanning them here would drop traps the production build still needs.
#
# Two exclusions, both load-bearing:
#   - recomp_stubs_recovery.c is this script's own output. Counting its bodies
#     as "defined" would make the next run emit nothing and the traps would
#     vanish on the second run.
#   - gen/fixtures/ holds the fixture subset, which overlaps production on
#     purpose. A trap that only the fixture defines is still unresolved in the
#     game, and dropping it there is how sub_0018CEB0 and four others silently
#     lost their traps.
def _suppresses_a_trap(source):
    if source.name=='recomp_stubs_recovery.c':
        return True
    return 'fixtures' in source.parts

defined=set()
traps=set()
for source in (root/'src').rglob('*.c'):
    if _suppresses_a_trap(source):continue
    contents=source.read_text(encoding='utf-8')
    defined.update(re.findall(r'\bvoid\s+(\w+)\(void\)\s*\{',contents))
    traps.update(re.findall(r'\bvoid\s+(\w+)\(void\)\s*\{\s*recomp_icall_fail_log',contents))
missing={a:name for a,name in translator.lifter.referenced_calls.items() if name not in defined}
recovery_trap_lines=[]
if missing:
    recovery_trap_lines.append('/* Newly exposed recovery dependencies: diagnostic traps only. */')
    for address,name in sorted(missing.items()):
        recovery_trap_lines.append(f'void {name}(void) {{ recomp_icall_fail_log(0x{address:08X}u); abort(); }}')
recovery_trap_path=root/'src/recomp/gen/recomp_stubs_recovery.c'
recovery_trap_path.write_text(
    '/* Generated by scripts/recover-functions.py; traps for direct calls the reviewed\n'
    ' * recovery bodies expose that no production translation defines yet.\n'
    ' *\n'
    ' * Separate from recomp_stubs_unresolved.c on purpose: that file and\n'
    ' * recomp_funcs.h come from one full translate_batch_split pass and must stay\n'
    ' * consistent with each other. This script translates only the reviewed\n'
    ' * entries and cannot speak for the rest of the database. */\n'
    '#define RECOMP_GENERATED_CODE\n'
    '#include "recomp_funcs.h"\n'
    '#include <stdlib.h>\n\n'
    +('\n'.join(recovery_trap_lines) if recovery_trap_lines else '')
    +'\n',encoding='utf-8')
# The focused fixtures hand-write counted seams for a few of the same trap
# addresses, so linking the whole unresolved unit into a fixture target would
# collide.  Derive the complementary subset from the finished production trap
# set and leave the overlapping addresses to the fixtures.  Production keeps
# every trap.
#
# The production trap set is the union of two files that this script no longer
# conflates: the full pass's recomp_stubs_unresolved.c and this script's own
# recomp_stubs_recovery.c.  Read them back rather than trusting an in-memory
# variable, so the fixture subset always matches what the production target
# actually compiles.
# A focused fixture target links three things: the hand-written test, the
# generated body file for its unit, and this complement.  Both of the first two
# define symbols, so both must be subtracted -- scanning only tests/ missed the
# unit bodies and the fixture failed to link with
# LNK2005: sub_00191390 already defined in recovered_11c1_test.obj, because the
# unit file compiles the very bodies this complement was still trapping.
fixture_own=set()
for fixture in list((root/'tests').glob('test_recovery_*.c')) + \
        list((root/'src/recomp/recovered').glob('recovered_*_test.c')):
    fixture_own.update(re.findall(r'\bvoid\s+(\w+)\(void\)\s*\{',
                                  fixture.read_text(encoding='utf-8')))
def _keep(line):
    match=re.match(r'^void\s+(\w+)\(void\)\s*\{',line)
    return not (match and match.group(1) in fixture_own)
production_trap_lines=[]
for _trap_file in ('recomp_stubs_unresolved.c','recomp_stubs_recovery.c'):
    _p=root/'src/recomp/gen'/ _trap_file
    if _p.exists():
        production_trap_lines.extend(_p.read_text(encoding='utf-8').splitlines())
recovery_stubs=[line for line in production_trap_lines
                if _keep(line) and not line.startswith('/* Newly exposed recovery')]
already_trapped={re.match(r'^void\s+(\w+)',line).group(1)
                 for line in recovery_stubs
                 if re.match(r'^void\s+(\w+)\(void\)\s*\{',line)}
# A focused fixture compiles only its unit's bodies, so a callee that the
# production build resolves from another generated chunk -- or from a trap the
# production set already carries -- is still an undefined symbol there.  Emit a
# trap for every unit reference that no unit body defines, minus the ones the
# fixtures define themselves.  Production is unaffected: it links the real
# chunk and the full trap set.
unit_defined={int(e['start'],16) for e in entries}
fixture_refs=set()
for unit,addresses in test_units.items():
    for address in addresses:
        fixture_refs.update(re.findall(r'RECOMP_ABI_CALL\(0x([0-9A-Fa-f]{8})u',
                                       rendered[address][0]))
extra_traps=sorted(a for a in fixture_refs
                   if int(a,16) not in unit_defined
                   and f'sub_{a.upper()}' not in fixture_own
                   and f'sub_{a.upper()}' not in already_trapped)
if extra_traps:
    recovery_stubs.append('\n/* Callees this unit does not compile: trap only in the fixture. */')
    for address in extra_traps:
        recovery_stubs.append(f'void sub_{address.upper()}(void) {{ '
                              f'recomp_icall_fail_log(0x{address.upper()}u); abort(); }}')
# Written to its own subdirectory, NOT to src/recomp/gen/ directly.
#
# The production target globs src/recomp/gen/*.c into jsrf_recomp, so a fixture
# file left in that directory gets compiled into the game as well as into the
# recovery test. Once the clobbering fix let recomp_stubs_unresolved.c hold its
# real 274 stubs, every address this file also defines became a duplicate
# symbol: LNK2005 ... already defined in recomp_stubs_recovery_test.obj, dozens
# of them, then LNK1169. The fixture subset and the production set deliberately
# overlap, so the two must never be linked into one binary.
fixture_stub_dir=root/'src/recomp/gen/fixtures'
fixture_stub_dir.mkdir(parents=True,exist_ok=True)
# Remove a copy an earlier version of this script wrote into the globbed
# directory; CMake would keep compiling it and the link would keep colliding.
_stale_fixture=root/'src/recomp/gen/recomp_stubs_recovery_test.c'
if _stale_fixture.exists():
    _stale_fixture.unlink()
(fixture_stub_dir/'recomp_stubs_recovery_test.c').write_text(
    '/* Generated by scripts/recover-functions.py; the unresolved-trap subset that the\n'
    ' * focused recovery fixtures do not define themselves.  Linking the full\n'
    ' * recomp_stubs_unresolved.c into a fixture unit would collide with the\n'
    ' * counted seams those tests hand-write, so the overlapping addresses are\n'
    ' * dropped here and left to each fixture.  Production keeps every trap.\n'
    ' *\n'
    ' * Lives in gen/fixtures/ so the production glob of gen/*.c cannot pick it up:\n'
    ' * production and fixtures define an overlapping set on purpose, so sharing a\n'
    ' * binary always fails the link. */\n'
    +'\n'.join(recovery_stubs)+'\n',encoding='utf-8')
pending={a:name for a,name in translator.lifter.referenced_calls.items() if name not in defined or name in traps}
(root/'config/recovery-unresolved.json').write_text(json.dumps({f'0x{a:08X}':n for a,n in sorted(pending.items())},indent=2)+'\n')
# External definitions include generated recovery bodies as well as manual CRT.
manual_path=root/'config/manual-functions.json'
manual=json.loads(manual_path.read_text())
for entry in entries:
    address=int(entry['start'],16);manual[f'0x{address:08X}']=f'sub_{address:08X}'
manual_path.write_text(json.dumps(manual,indent=2)+'\n')
# Preserve reviewed entries as input for any future complete regeneration.
merged=[]
for address,item in sorted(database.items()):
    item=dict(item);item.pop('_addr',None);item['end']=f"0x{item['end']:08X}"
    merged.append(item)
(root/'tools/disasm/output/functions.recovered.json').write_text(json.dumps(merged,indent=2)+'\n')
print(f'Recovered {len(entries)} functions into {output}')
