"""Every guest address the running binary can resolve to a body.

An indirect call traps only when the address it carries is in *none* of the
three tables the runtime consults, in this order:

  1. `jsrf_lookup_recovered` in `src/recomp/recovered/recovered.c`, generated by
     `scripts/recover-functions.py` from `config/recovered-functions.json`.
  2. `recomp_lookup_manual` in `src/recomp_manual.c`, driven by
     `config/manual-functions.json`.
  3. the generated dispatch table `g_recomp_table` in
     `src/recomp/gen/recomp_dispatch.c`.

The two span detectors used to test against the reviewed manifest alone, and
later against the manifest unioned with the disassembler's own database.  Both
sets are wrong in the same direction: the manifest lists the *reviewed* entries
(3071) while the generated dispatch covers 8768 addresses, so an address that
already resolves looks uncovered.  That is what turned six working entries of
the class dispatch table at `0x0020D2B8` -- `0x0007C4B0`, `0x0007C800`,
`0x00011C90`, `0x0007D000`, `0x0007D3D0`, `0x0007D120`, `0x0007D290` -- into a
"next packet" that needed no work at all.

Reading the generated sources rather than the config files is deliberate: the
question is what the binary resolves, and the generated dispatch is the thing
that actually runs.  It also means this needs no rebuild to be accurate.
"""
from pathlib import Path
import json
import re

RECOVERED_SWITCH = re.compile(r'case 0x([0-9A-Fa-f]+)u:\s*return sub_')
DISPATCH_ENTRY = re.compile(r'\{\s*0x([0-9A-Fa-f]+)u,\s*\(recomp_func_t\)(\w+)\s*\}')


def runtime_starts(root):
    """Return (covered, origin) for every address the runtime can resolve.

    `covered` maps a VA to a short string naming the table that answers it, so a
    caller can report *how* an address resolves and not only that it does.
    """
    root = Path(root)
    covered = {}

    recovered = root / 'src' / 'recomp' / 'recovered' / 'recovered.c'
    if recovered.exists():
        text = recovered.read_text(encoding='utf-8', errors='replace')
        marker = text.find('recomp_func_t jsrf_lookup_recovered')
        if marker >= 0:
            for match in RECOVERED_SWITCH.finditer(text[marker:]):
                covered.setdefault(int(match.group(1), 16), 'recovered')

    manual = root / 'config' / 'manual-functions.json'
    if manual.exists():
        for key in json.loads(manual.read_text()):
            try:
                covered.setdefault(int(key, 16), 'manual')
            except ValueError:
                pass

    dispatch = root / 'src' / 'recomp' / 'gen' / 'recomp_dispatch.c'
    if dispatch.exists():
        text = dispatch.read_text(encoding='utf-8', errors='replace')
        for match in DISPATCH_ENTRY.finditer(text):
            covered.setdefault(int(match.group(1), 16), 'dispatch')

    return covered
