"""Every guest address the running binary can resolve to a body.

An indirect call traps only when the address it carries is in *none* of the
three tables the runtime consults, in this order:

  1. `jsrf_lookup_recovered` in `src/recomp/recovered/recovered.c`, generated by
     `scripts/recover-functions.py` from `config/recovered-functions.json`.
  2. `recomp_lookup_manual` in `src/recomp_manual.c`, driven by
     `config/manual-functions.json`.
  3. the generated dispatch table `g_recomp_table` in
     `src/recomp/gen/recomp_dispatch.c`.

The two span detectors used to test against the reviewed manifest alone, and
later against the manifest unioned with the disassembler's own database.  Both
sets are wrong in the same direction: the manifest lists the *reviewed* entries
(3071) while the generated dispatch covers 8768 addresses, so an address that
already resolves looks uncovered.  That is what turned six working entries of
the class dispatch table at `0x0020D2B8` -- `0x0007C4B0`, `0x0007C800`,
`0x00011C90`, `0x0007D000`, `0x0007D3D0`, `0x0007D120`, `0x0007D290` -- into a
"next packet" that needed no work at all.

Reading the generated sources rather than the config files is deliberate: the
question is what the binary resolves, and the generated dispatch is the thing
that actually runs.  It also means this needs no rebuild to be accurate.
"""
from pathlib import Path
import json
import re

RECOVERED_SWITCH = re.compile(r'case 0x([0-9A-Fa-f]+)u:\s*return (\w+);')
DISPATCH_ENTRY = re.compile(r'\{\s*0x([0-9A-Fa-f]+)u,\s*\(recomp_func_t\)(\w+)\s*\}')


def runtime_starts(root):
    """Return (covered, origin) for every address the runtime can resolve.

    `covered` maps a VA to a short string naming the table that answers it, so a
    caller can report *how* an address resolves and not only that it does.
    """
    root = Path(root)
    covered = {}

    recovered = root / 'src' / 'recomp' / 'recovered' / 'recovered.c'
    if recovered.exists():
        text = recovered.read_text(encoding='utf-8', errors='replace')
        marker = text.find('recomp_func_t jsrf_lookup_recovered')
        if marker >= 0:
            for match in RECOVERED_SWITCH.finditer(text[marker:]):
                covered.setdefault(int(match.group(1), 16), 'recovered')

    manual = root / 'config' / 'manual-functions.json'
    if manual.exists():
        for key in json.loads(manual.read_text()):
            try:
                covered.setdefault(int(key, 16), 'manual')
            except ValueError:
                pass

    dispatch = root / 'src' / 'recomp' / 'gen' / 'recomp_dispatch.c'
    if dispatch.exists():
        text = dispatch.read_text(encoding='utf-8', errors='replace')
        for match in DISPATCH_ENTRY.finditer(text):
            covered.setdefault(int(match.group(1), 16), 'dispatch')

    return covered


def genuine_starts(root):
    """Addresses whose *own* symbol answers them, not a folded parent's.

    `runtime_starts()` answers "can the runtime resolve this address", and for a
    `tail_jump_alias` folded into its parent by the `ff4d442` abutting-alias rule
    the answer is **yes** -- the dispatch tuple names the parent's symbol.  That
    makes the two questions indistinguishable to a caller that only asks
    `target in starts`, and the difference is exactly the A2e/A2f/A2g defect:

        { 0x0003060Eu, (recomp_func_t)sub_00030570 },

    `0x0003060E` resolves, so a branch to it looks like a tail call to a real
    entry.  It is not: entering it runs `sub_00030570`'s body from its first
    byte, which is a different function.

    This returns the subset where the answering symbol is the address's own, so
    a caller can tell "a tail call to a real entry" from "a branch into a body
    that the fold reassigned".  Callers that want *resolvability* keep using
    `runtime_starts()`; this is for callers asking whether an address is an
    entry in its own right.
    """
    root = Path(root)
    genuine = {}

    recovered = root / 'src' / 'recomp' / 'recovered' / 'recovered.c'
    if recovered.exists():
        text = recovered.read_text(encoding='utf-8', errors='replace')
        marker = text.find('recomp_func_t jsrf_lookup_recovered')
        if marker >= 0:
            for match in RECOVERED_SWITCH.finditer(text[marker:]):
                va = int(match.group(1), 16)
                if match.group(2).lower() == 'sub_%08x' % va:
                    genuine.setdefault(va, 'recovered')

    manual = root / 'config' / 'manual-functions.json'
    if manual.exists():
        for key, name in json.loads(manual.read_text()).items():
            try:
                va = int(key, 16)
            except ValueError:
                continue
            if str(name).lower() == 'sub_%08x' % va:
                genuine.setdefault(va, 'manual')

    dispatch = root / 'src' / 'recomp' / 'gen' / 'recomp_dispatch.c'
    if dispatch.exists():
        text = dispatch.read_text(encoding='utf-8', errors='replace')
        for match in DISPATCH_ENTRY.finditer(text):
            va = int(match.group(1), 16)
            if match.group(2).lower() == 'sub_%08x' % va:
                genuine.setdefault(va, 'dispatch')

    # A reviewed manifest entry is an entry by definition: it was added because
    # the address needs its own body and its own dispatch tuple.
    entries = root / 'config' / 'recovered-functions.json'
    if entries.exists():
        for entry in json.loads(entries.read_text()):
            genuine.setdefault(int(entry['start'], 16), 'manifest')

    return genuine
